'''
Read the period-velocity spectrum (units: s-in/s) generated by simqke for a 0.02 damping and convert the data to a period-acceleration spectrum (units: s-m/s2) and plot this spectrum.

'''
import math
import matplotlib.pyplot as plt
# data
damping=2 # damping % (to add information this information in graphics)
simqke_spectr_fileNm='simqke_T_vel_spectrum_damp2.txt'
# damping=2 # damping % (to add information this information in graphics)
# simqke_spectr_fileNm='simqke_T_vel_spectrum_damp5.txt'

in2m=0.0254
def is_number(s):
    try:
        float(s)
    except ValueError:  # Failed
        return False
    else:  # Succeeded
        return True
period=list()
velocity_in_s=list()
with open(simqke_spectr_fileNm, 'r') as f:
    for line in f:
        if not line.strip():
            continue
        fields= line.split()
        if(is_number(fields[0])):
            period.append(float(fields[0]))
            velocity_in_s.append(float(fields[2]))
            
accel_m_s2=list()

for i in range(len(period)):
    T=period[i]
    v=velocity_in_s[i]*in2m # velocity in m/s
    w=2*math.pi*1/T # angular velocity
    accel=v*w
    accel_m_s2.append(abs(accel))
    
# Plot velocity spectogram (vel. en in/s)
velocity_in_s=[abs(v) for v in velocity_in_s]
plt.figure(figsize=(10, 5))
plt.plot(period, velocity_in_s)
plt.title('Period spectrum of the accelerogram in velocities. Damping='+str(damping)+'%')
plt.xlabel('Period (s)')
plt.xscale('log')
plt.ylabel('Velocity $(in/s)$')
plt.yscale('log')

#plt.xlim(0,3) # Zoom en el rango de periodos de interés
plt.fill_between(period,velocity_in_s,alpha=0.1)
plt.grid(True)
plt.show()

    
'''    
# Plot period spectogram (accel en m/s2)
plt.figure(figsize=(10, 5))
plt.plot(period, accel_m_s2)
plt.title('Period spectrum of the accelerogram. Damping='+str(damping)+'%')
plt.xlabel('Period (s)')
plt.ylabel('Acceleration $(m/s^2)$')
plt.xlim(0,3) # Zoom en el rango de periodos de interés
plt.fill_between(period,accel_m_s2,alpha=0.1)
plt.grid(True)
plt.show()
'''
import scipy
g=scipy.constants.g
accel_g=[a/g for a in accel_m_s2]
# Plot period spectogram (accel en g)
plt.figure(figsize=(10, 5))
plt.plot(period, accel_g)
plt.title('Period spectrum of the accelerogram. Damping='+str(damping)+'%')
plt.xlabel('Period (s)')
plt.ylabel('Acceleration (g)')
plt.xlim(0,3) # Zoom en el rango de periodos de interés
plt.fill_between(period,accel_g,color='r',alpha=0.1)
plt.grid(True)
plt.show()

    

    
